// Generated by CoffeeScript 1.6.3
(function() {
  var doc;
  doc = document;
  return doc.addEventListener('DOMContentLoaded', function() {
    var CountDown;
    CountDown = function() {
      var MARGIN_LEFT, MARGIN_TOP, RADIUS, WINDOW_HEIGHT, WINDOW_WIDTH, ball, canvas, context, curShowTimeSeconds, endTime, self;
      self = this;
      WINDOW_WIDTH = 1024;
      WINDOW_HEIGHT = 768;
      MARGIN_TOP = 60;
      MARGIN_LEFT = 30;
      canvas = doc.getElementById('canvas');
      canvas.width = WINDOW_WIDTH;
      canvas.height = WINDOW_HEIGHT;
      context = canvas.getContext('2d');
      RADIUS = 8;
      ball = {
        x: 512,
        y: 100,
        r: 20,
        g: 2,
        vx: -4,
        vy: 0,
        color: '#005588'
      };
      endTime = new Date(2014, 6, 28, 20, 18, 22);
      curShowTimeSeconds = 0;
      /*
       * 倒计时
      */

      this.getCurrentShowTimeSeconds = function() {
        var curTime, ret;
        curTime = new Date();
        ret = endTime.getTime() - curTime.getTime();
        ret = Math.round(ret / 1000);
        if (ret < 0) {
          ret = 0;
        }
        return ret;
      };
      /*
       *
      */

      this.update = function() {
        var curHours, curMinutes, curSeconds, nextHours, nextMinutes, nextSeconds, nextShowTimeSeconds;
        nextShowTimeSeconds = self.getCurrentShowTimeSeconds();
        nextHours = parseInt(nextShowTimeSeconds / 3600);
        nextMinutes = parseInt((nextShowTimeSeconds - nextHours * 3600) / 60);
        nextSeconds = nextShowTimeSeconds % 60;
        curHours = parseInt(curShowTimeSeconds / 3600);
        curMinutes = parseInt((curShowTimeSeconds - nextHours * 3600) / 60);
        curSeconds = curShowTimeSeconds % 60;
        if (nextSeconds !== curSeconds) {
          curShowTimeSeconds = nextShowTimeSeconds;
        }
      };
      /*
       * 渲染每个字
       * @param {Number} x    每个点的x坐标
       * @param {Number} y    每个点得y坐标
       * @param {String} num  要渲染的字
       * @param {Object} ctx  画布
       * @return
      */

      this.renderDigit = function(x, y, num, ctx) {
        var _i, _index_i, _index_j, _item_i, _item_j, _j, _len, _len1, _ref, _ref1;
        ctx.fillStyle = '#00f';
        _ref = digit[num];
        for (_item_i = _i = 0, _len = _ref.length; _i < _len; _item_i = ++_i) {
          _index_i = _ref[_item_i];
          _ref1 = digit[num][_item_i];
          for (_item_j = _j = 0, _len1 = _ref1.length; _j < _len1; _item_j = ++_j) {
            _index_j = _ref1[_item_j];
            if (digit[num][_item_i][_item_j] === 1) {
              ctx.beginPath();
              ctx.arc(x + _item_j * 2 * (RADIUS + 1) + (RADIUS + 1), y + _item_i * 2 * (RADIUS + 1) + (RADIUS + 1), RADIUS, 0, 2 * Math.PI);
              ctx.closePath();
              ctx.fill();
            }
          }
        }
      };
      /*
       * 渲染画布
       * @param {Object} ctx  画布
       * @return
      */

      this.render = function(ctx) {
        var hours, minutes, seconds;
        hours = parseInt(curShowTimeSeconds / 3600);
        minutes = parseInt((curShowTimeSeconds - hours * 3600) / 60);
        seconds = curShowTimeSeconds % 60;
        ctx.clearRect(0, 0, WINDOW_WIDTH, WINDOW_HEIGHT);
        self.renderDigit(MARGIN_LEFT, MARGIN_TOP, parseInt(hours / 10), ctx);
        self.renderDigit(MARGIN_LEFT + 15 * (RADIUS + 1), MARGIN_TOP, parseInt(hours % 10), ctx);
        self.renderDigit(MARGIN_LEFT + 30 * (RADIUS + 1), MARGIN_TOP, 10, ctx);
        self.renderDigit(MARGIN_LEFT + 39 * (RADIUS + 1), MARGIN_TOP, parseInt(minutes / 10), ctx);
        self.renderDigit(MARGIN_LEFT + 54 * (RADIUS + 1), MARGIN_TOP, parseInt(minutes % 10), ctx);
        self.renderDigit(MARGIN_LEFT + 69 * (RADIUS + 1), MARGIN_TOP, 10, ctx);
        self.renderDigit(MARGIN_LEFT + 78 * (RADIUS + 1), MARGIN_TOP, parseInt(seconds / 10), ctx);
        self.renderDigit(MARGIN_LEFT + 93 * (RADIUS + 1), MARGIN_TOP, parseInt(seconds % 10), ctx);
      };
      /*
       * 初始化
      */

      this.init = function() {
        curShowTimeSeconds = self.getCurrentShowTimeSeconds();
        setInterval(function() {
          self.render(context);
          self.update();
        }, 50);
      };
    };
    return new CountDown().init();
  });
})();
