// Generated by CoffeeScript 1.6.3
(function() {
  var MARGIN_LEFT, MARGIN_TOP, RADIUS, SCREEN_HEIGHT, SCREEN_WIDTH, canvas, context, doc, renderDigit;
  SCREEN_WIDTH = 1024;
  SCREEN_HEIGHT = 768;
  MARGIN_TOP = 60;
  MARGIN_LEFT = 30;
  RADIUS = 8;
  doc = document;
  canvas = doc.getElementById('canvas');
  context = canvas.getContext('2d');
  canvas.width = SCREEN_WIDTH;
  canvas.height = SCREEN_HEIGHT;
  /*
   * 渲染字体
   * @param {Number}  x    球距离左侧距离 
   * @param {Number}  y    球距离顶部距离
   * @param {String}  num  要渲染的数字和符号
   * @param {Object}  ctx  画布对象
  */

  renderDigit = function(x, y, num, ctx) {
    var _i, _index_i, _index_j, _item_i, _item_j, _j, _len, _len1, _ref, _ref1;
    ctx.fillStyle = "rgb(0, 102, 153)";
    _ref = digit[num];
    for (_item_i = _i = 0, _len = _ref.length; _i < _len; _item_i = ++_i) {
      _index_i = _ref[_item_i];
      console.log(_item_i);
      _ref1 = digit[num][_item_i];
      for (_item_j = _j = 0, _len1 = _ref1.length; _j < _len1; _item_j = ++_j) {
        _index_j = _ref1[_item_j];
        if (digit[num][_item_i][_item_j] === 1) {
          ctx.beginPath();
          ctx.arc(x + _item_j * 2 * (RADIUS + 1) + (RADIUS + 1), y + _item_i * 2 * (RADIUS + 1) + (RADIUS + 1), RADIUS, 0, 2 * Math.PI);
          ctx.closePath();
          ctx.fill();
        }
      }
    }
  };
  renderDigit(MARGIN_LEFT, MARGIN_TOP, 0, context);
})();
